blog_app/urls.py
from django.urls import path
from blog_app import views

app_name = 'blog_app'
urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/new/', views.PostCreateView.as_view(), name='post_new'),
    path('post/<int:pk>/edit/', views.PostUpdateView.as_view(), name='post_edit'),
    path('post/<int:pk>/remove/', views.PostDeleteView.as_view(), name='post_remove'),
    path('draft/', views.DraftListView.as_view(), name='post_draft_list'),
    path('post/<int:pk>/comment', views.CommentFormView.as_view(), name='add_comment_to_post'),
    path('comment/<int:pk>/approve/', views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),
    path('post/<int:pk>/publish/', views.post_publish, name='post_publish'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog_app.urls')),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(), name='logout', kwargs={'next_page':'/'}),
]

blog_app/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default = timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def get_absolute_url(self):
        return reverse('blog_app:post_detail', kwargs={'pk':self.pk})

    def approve_comments(self):
        return self.comments.filter(approved_comment=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey('blog_app.Post', related_name='comments', on_delete=models.CASCADE)
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('blog_app:post_list')

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

blog_app/forms.py
from django import forms
from blog_app.models import Post, Comment

class PostForm(forms.ModelForm):

    class Meta():
        model = Post
        fields = ('author', 'title', 'text')
        widgets = {
            'title':forms.TextInput(attrs={'class':'textinputclass'}),
            'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent', 'cols': 15})
        }


class CommentForm(forms.ModelForm):

    class Meta():
        model = Comment
        fields = ('author', 'text')
        widgets = {
            'author':forms.TextInput(attrs={'class':'textinputclass'}),
            'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent'})
        }

blog_app/views.py
from django.shortcuts import get_object_or_404, redirect
from blog_app.models import Post, Comment
from blog_app.forms import PostForm, CommentForm
from django.views.generic import TemplateView, DetailView, ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.utils import timezone


# Create your views here.
class AboutView(TemplateView):
    template_name = 'blog_app/about.html'

class PostListView(ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

class PostDetailView(DetailView):
    model = Post

@method_decorator(login_required, name='dispatch')
class PostCreateView(CreateView):
    model = Post
    login_url = '/login/'
    redirect_field_name = 'blog_app/post_detail.html'
    form_class = PostForm

@method_decorator(login_required, name='dispatch')
class PostUpdateView(UpdateView):
    login_url = '/login/'
    redirect_field_name = 'blog_app/post_detail.html'
    model = Post
    form_class = PostForm

@method_decorator(login_required, name='dispatch')
class PostDeleteView(DeleteView):
    login_url = '/login/'
    redirect_field_name = 'blog_app/post_detail.html'
    model = Post
    success_url = reverse_lazy('blog_app:post_list')

@method_decorator(login_required, name='dispatch')
class DraftListView(ListView):
    login_url = '/login/'
    redirect_field_name = 'blog_app/post_list.html'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by('created_date')

class CommentFormView(FormView):
    template_name = 'blog_app/comment_form.html'
    form_class = CommentForm
    success_url = reverse_lazy('blog_app:post_detail/pk')

    def form_valid(self, form):
        post = get_object_or_404(Post, pk=self.kwargs["pk"])
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
        return redirect('blog_app:post_detail', pk=post.pk)


###########################################################################

@login_required
def comment_approve(request,pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog_app:post_detail', pk=comment.post.pk)

@login_required
def comment_remove(request,pk):
    comment = get_object_or_404(Comment,pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('blog_app:post_detail', pk=post_pk)

@login_required
def post_publish(request,pk):
    post = get_object_or_404(Post,pk=pk)
    post.publish()
    return redirect('blog_app:post_detail', pk=pk)

blog_app/templates/blog_app/about.html
{% extends 'blog_app/base.html' %}

{% block title %}
  <title>About Page</title>
{% endblock %}

{% block main %}
  <main class="main-structure">
    <h1>About our Family</h1>
  </main>
{% endblock %}

blog_app/templates/blog_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="utf-8">
    {% block title %}
    {% endblock %}
    <!-- https://github.com/yabwe/medium-editor -->
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

    <link rel="stylesheet" href="{% static 'blog_app/css/blog.css' %}">
    <script src="{% static 'blog_app/js/script.js' %}" type="text/javascript" defer></script>

    <!-- fonts -->
  </head>
  <body>

    <header class="nav-bar nav-bar-structure">
      <a id="home" href="{% url 'blog_app:post_list' %}">Our Blog</a>
      <a href="{% url 'blog_app:about' %}">About</a>
    </header>

    <aside class="nav-bar aside-structure">
      <nav class="aside-nav-structure">
        {% if user.is_authenticated %}
          <a href="{% url 'blog_app:post_new'%}">New Post</a>
          <a href="{% url 'blog_app:post_draft_list' %}">Drafts</a>
          <a href="{% url 'logout' %}">Sign Out</a>
          <p class="no-margin">Welcome: {{ user.username }}</p>
        {% else %}
          <a class="sign-in" href="{% url 'login' %}">Sign In!</a>
        {% endif %}
      </nav>
    </aside>

    {% block main %}
    {% endblock %}

  </body>
</html>

blog_app/templates/blog_app/comment_form.html
{% extends 'blog_app/base.html' %}


{% block title %}
  <title>New Comment Form</title>
{% endblock %}

{% block main %}
  <main class="main-structure">
    <h1>New Comment</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button class="btn" type="submit">Post Comment</button>
    </form>
  </main>
{% endblock %}

blog_app/templates/blog_app/post_confirm_delete.html
{% extends 'blog_app/base.html' %}

{% block title %}
  <title>Confirm Delete</title>
{% endblock %}

{% block main %}
  <main class="main-structure">
    <form method="post">
      {% csrf_token %}
      <p>Are you sure you want to delete {{ object }}?</p>
      <input class="btn" type="submit" value="Confirm">
    </form>
  </main>
{% endblock %}

blog_app/templates/blog_app/post_detail.html
{% extends 'blog_app/base.html' %}

{% block title %}
  <title>Blog Post</title>
{% endblock %}

{% block main %}
  <main class="main-structure">
    <h1>{{ post.title }}</h1>
    {% if post.published_date %}
      <p class="utc-time">{{ post.published_date }}</p>
    {% else %}
      <a class="no-hover" href="{% url 'blog_app:post_publish' pk=post.pk %}"><button class="btn">Publish</button></a>
    {% endif %}

    <p>{{ post.text|safe|linebreaksbr }}</p>

    {% if user.is_authenticated %}
    <a class="no-hover" href="{% url 'blog_app:post_edit' pk=post.pk %}"><button class="btn">Edit</button></a>
    <a class="no-hover" href="{% url 'blog_app:post_remove' pk=post.pk %}"><button class="btn btn-warning">Remove</button></a>
    {% endif %}

    <hr>

    <a class="no-hover" href="{% url 'blog_app:add_comment_to_post' pk=post.pk %}"><button class="btn margin-bottom">Add Comment</button></a>

    {% for comment in post.comments.all %}
      <br>
      {% if user.is_authenticated or comment.approved_comment %}
        {{ comment.created_date }}
        {% if not comment.approved_comment %}
          <a class="no-hover" href="{% url 'blog_app:comment_approve' pk=comment.pk %}"><button class="btn">Approve</button></a>
          <a class="no-hover" href="{% url 'blog_app:comment_remove' pk=comment.pk %}"><button class="btn btn-warning">Remove</button></a>
        {% endif %}

        <p>{{ comment.text|safe|linebreaksbr }}</p>
        <p>Posted by: {{ comment.author }}</p>
      {% endif %}

      {% empty %}
      <p>No Comments!</p>

    {% endfor %}
  </main>

{% endblock %}

blog_app/templates/blog_app/post_draft_list.html
{% extends 'blog_app/base.html' %}

{% block title %}
  <title>Post Drafts</title>
{% endblock %}

{% block main %}
  <main class="main-structure">
    {% for post in posts %}
      <p>Created: {{ post.created_date|date:'D-M-Y' }}</p>
      <h1><a href="{% url 'blog_app:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
      <p>{{ post.text|truncatechars:200 }}</p>
    {% endfor %}
  </main>
{% endblock %}

blog_app/templates/blog_app/post_form.html
{% extends 'blog_app/base.html' %}

{% block title %}
  <title>New Post Form</title>
{% endblock %}

{% block main %}
  <main class="main-structure">
    <h1>New Post</h1>
    <form method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <button class="btn" type="submit">Save</button>
    </form>
  </main>
{% endblock %}

blog_app/templates/blog_app/post_list.html
{% extends 'blog_app/base.html' %}

{% block title %}
  <title>Home</title>
{% endblock %}

{% block main %}
  <main class="main-structure">
    {% for post in post_list %}
    <h1><a href="{% url 'blog_app:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
    <p>Published on: {{post.published_date|date:"D M Y"}}</p>
    <a href="{% url 'blog_app:post_detail' pk=post.pk %}">Comments: {{post.approve_comments.count}}</a>
    {% endfor %}
  </main>
{% endblock %}